//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClientConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKeyRepository")]
    public interface IKeyRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeyRepository/WriteKey", ReplyAction="http://tempuri.org/IKeyRepository/WriteKeyResponse")]
        void WriteKey(string institution, string group, string product, string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKeyRepositoryChannel : ServiceClientConsole.ServiceReference1.IKeyRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeyRepositoryClient : System.ServiceModel.ClientBase<ServiceClientConsole.ServiceReference1.IKeyRepository>, ServiceClientConsole.ServiceReference1.IKeyRepository {
        
        public KeyRepositoryClient() {
        }
        
        public KeyRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeyRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteKey(string institution, string group, string product, string key) {
            base.Channel.WriteKey(institution, group, product, key);
        }
    }
}
